name: BinoFlex
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73874
title: BinoFlex
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8ad039'
    - '#0e1b47'
    - '#038000'
    - '#ae1f23'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.1605312628671527
purpose: []
