name: BinoFlex
favicon: null
layout_spectrum: 0.0695143616758287
typography_spectrum: 0.7121037056203932
title: BinoFlex
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.32242518570274115
  lightness: 0.869252999778837
  saturation: 0.05275763035751879
  rhythmicContrast: 0.1605312628671527
purpose: []
